[workspace]
members = [
    "bdk-tokio-electrum",
    "tokio-electrum",
]
default-members = ["tokio-electrum"]
resolver = "2"

[workspace.package]
authors = ["Yuki Kishimoto <yukikishimoto@protonmail.com>"]
homepage = "https://github.com/shadowylab/tokio-electrum"
repository = "https://github.com/shadowylab/tokio-electrum.git"
license = "MIT"

[workspace.dependencies]
tokio = { version = "1", default-features = false }
