[package]
name = "tokio-electrum"
version = "0.1.0"
edition = "2024"
description = "High-level Electrum client implementation, featuring automatic reconnection handling and real-time (block/scripts) updates."
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["bitcoin", "electrum", "tokio"]

[features]
default = ["socks"]
socks = ["dep:tokio-socks"]

[dependencies]
bitcoin = "0.32"
electrum_streaming_client = { git = "https://github.com/yukibtc/electrum_streaming_client", branch = "missing-features-req-patch", features = ["tokio"] }
futures = "0.3"
thiserror = "2.0"
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "sync", "time"] }
tokio-rustls = { version = "0.26", default-features = false, features = ["ring", "tls12"] }
tokio-socks = { version =  "0.5", optional = true }
tracing.workspace = true
webpki-roots = "1.0"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[[example]]
name = "electrum_client"
