[package]
name = "tokio-electrum"
version = "0.1.0"
edition = "2024"
description = "High-level Electrum client implementation, featuring automatic reconnection handling and real-time (block/scripts) updates."
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["bitcoin", "electrum", "tokio"]

[dependencies]
bitcoin = "0.32"
electrum_streaming_client = { git = "https://github.com/bitcoindevkit/electrum_streaming_client", rev = "d384cf2fa9640f0dbd7be25964b686ece6c92976", features = ["tokio"] }
futures = "0.3"
thiserror = "2.0"
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "sync", "time"] }
tokio-rustls = "0.26"
# tokio-socks = "0.5" # TODO: needed for the future, to support proxy
tracing = "0.1"
webpki-roots = "1.0"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[[example]]
name = "electrum_client"
