[package]
name = "bdk-tokio-electrum"
version = "0.1.0"
edition = "2024"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["bitcoin", "bdk", "electrum", "tokio"]

[dependencies]
bdk_core = "0.6"
futures = "0.3"
tokio = { workspace = true, features = ["sync"] }
tokio-electrum = { path = "../tokio-electrum", version = "0.1" }
tracing.workspace = true

[dev-dependencies]
bdk_wallet = "2.3"
testenv.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
